name: Test Face alignment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        pytorch-version: ['2.0.1', '2.2.2', '2.11.0']
        exclude:
          - python-version: '3.12'
            pytorch-version: '2.0.1'
          - python-version: '3.9'
            pytorch-version: '2.11.0'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install torch==${{ matrix.pytorch-version }} --index-url https://download.pytorch.org/whl/cpu
          if python3 -c "import torch; assert tuple(int(x) for x in torch.__version__.split('+')[0].split('.')[:2]) < (2,3)"; then
            pip install "numpy<2"
          fi
          pip install . pytest flake8
      - name: Test with pytest
        run: pytest test/
      - name: Lint with flake8
        run: flake8 .
