name: Test Face alignment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        pytorch-version: ['2.0.1', '2.2.2', '2.11.0']
        exclude:
          - python-version: '3.12'
            pytorch-version: '2.0.1'
          - python-version: '3.9'
            pytorch-version: '2.11.0'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install torch==${{ matrix.pytorch-version }} --index-url https://download.pytorch.org/whl/cpu
          if [[ "${{ matrix.pytorch-version }}" == "2.0.1" || "${{ matrix.pytorch-version }}" == "2.2.2" ]]; then
            echo "numpy<2" > /tmp/constraints.txt
            pip install . pytest flake8 -c /tmp/constraints.txt
          else
            pip install . pytest flake8
          fi
      - name: Test with pytest
        run: pytest test/
      - name: Lint with flake8
        run: flake8 .
